sudo: false
language: ruby
rvm:
- 2.3.1
- 2.5.0
before_install: gem install bundler -v 1.16.1
notifications:
  slack:
    secure: C80aaHhhcI+RuTpijDX/DIN+KMqxX0Sr/BbQhohE0rgTfquxhIPMo7rGBnMIuRvU5rjbfwngjfjEvIsxZ3h+1rpuI8Uao/jgwRh/0qLbAok2U0Nt2KPJN1e8SjQkHaSdcuxeNzAL5V4321KyYGmHP22uCRSkIUl+S2ep7wro5nN/wKzgOJdlX4y8nLCWVaDKRZBsP62ZxFO2exwsuSnv9YfS8fpNPbFedfi4wokJoU/V+63AX+iZuoVkrWCe2MEtgvomo1pySchS7XwUV7dn1Tglox31y61DucFOm5EmWaiGKCK5ly9EwaW9KQ02Ru1S5lLj0E9RVEWJSdYR7tVBZX0fRmQ6dcGRBmrT9w8oI6ONrm35uADc3lk2HSg+cm4Qbhm7sXF2OiHgERfWXeKEdxA7mnNwlmS94C+ZxIfno3Z6G+8Lw7uJkxI9S9SH2cpKElOMoL1KqdHQus5VA5JGicNfqcmFVCqUi/laR32QZlZHSl6y1BUNs4q2eEQAqtGMTeLdUmqwpkcUZvd0aMiFmnQguEbnn6YIGGPRClTcNJDnMh/c9DMKO7MPDWV4FFkKqNVb75UlWY68rNmowdctIGQh63FWJjOCCP3H5PJy+7b7V9/1tppUAimv+h1146meASvhtGed7YA7yTrF61Io4thoJxidErw3EdSgIYxBh9c=
